import type { Metadata } from "next";
import localFont from "next/font/local";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

import "./globals.css";
import AppHeader from "@/components/app.header";
import AppFooter from "@/components/app.footer";
import { Container } from "react-bootstrap";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppHeader/>
          <Container>
            {children}
          </Container>
        <AppFooter/>
        <ToastContainer />
      </body>
    </html>
  );
}
